linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - typecheck  # Disabled due to Go 1.23 compatibility issues; govet provides type checking

linters-settings:
  govet:
    check-shadowing: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude standard library from checks that may have false positives
    - path: _test\.go
      linters:
        - errcheck

