# This file is the configuration for golangci-lint.
# See https://golangci-lint.run/usage/configuration/ for more information.

version: 2

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude standard library from checks that may have false positives
    - path: _test\.go
      linters:
        - errcheck

