# This file is the configuration for golangci-lint.
# See https://golangci-lint.run/usage/configuration/ for more information.

version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

